services:
  web:
    image: brayam05/proyecto4-angular-js:latest
    ports:
      - "8084:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
